### ISSUE TITLE
x86 for Cloud 

### ISSUE THREAD

**Issue by ShalokShalom** [CypherpunkArmory/UserLAnd-Site#19]
Hi there ^.^

Could you say me, if the Cloud version does support x86 PCs?

Is this some form of desktop sharing or how does it work?

Thanks a lot

**Comment by corbinlc** [comment]
The cloud version is not released yet.  Well, you can download the client and such, but you cannot yet sign up.  When it is launched it will support x86.  It will launch a box for you in the cloud and connect you to it via a command line tool or via the UserLAnd app.  Connections will initially be over SSH, but VNC is also planned.

**Comment by ShalokShalom** [comment]
You might mention this in your documentation and your homepage then. Why is it announced, if not ready?
